#!/bin/sh

# ##############################################################################
#
#  Gradle start up script for POSIX generated by Gradle.
#
#  Important for running:
#
#  (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#      noncompliant, but you have some other compliant shell such as ksh or
#      bash, then to run this script, change /bin/sh in the shebang line
#      (the first line of this script) to /bin/ksh (or to the path of whichever
#      POSIX-compliant shell you prefer).
#
# (2)  This script uses unset, and some shell implementations (e.g. the original
#      Bourne Shell) do not support unset, and will fail on the use of unset.
#      If you're on such a system, you'll need to use a more capable shell.
#
# (3)  To make it easier for us to diagnose issues when we run our own tests,
#      we use the -x flag of the shell to echo every single command that the
#      shell is executing. We then filter out some of the uninteresting commands
#      (like the ones setting the trap) to not overwhelm you with too much
#      output. We still leave the important ones, though, to help us debug
#      problems should they occur.
#
# ##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`echo -n "$PATH" | sed -e 's/;/ /g'`
    for d in $ROOTDIRSRAW
    do
        if [ -d "$d" ] ; then
            ROOTDIRS="$ROOTDIRS $d"
        fi
    done
    ROOTDIRS=`echo -n "$ROOTDIRS" | sed -e 's/^ //'`
    ARGS=
    for p in "$@"
    do
        case "$p" in
            -D*) ;&
            -d*) ;&
            -D*=*)
                # We have an options argument; add it as is
                ARGS="$ARGS \"$p\""
                ;;
            *)
                # We have a non-option argument; convert it to cygpath if needed
                if [ "$cygwin" = "true" -a "$msys" = "false" ] ; then
                    ARGS="$ARGS \"`cygpath --path --ignore --mixed "$p"`\""
                else
                    ARGS="$ARGS \"$p\""
                fi
                ;;
        esac
    done
else
    # Just escape the args so spaces and other special characters in them are not interpreted
    ARGS=""
    for p in "$@"
    do
        ARGS="$ARGS \"$p\""
    done
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$ARGS"

# by using 'eval', we can also use JAVA_OPTS and GRADLE_OPTS variables in here
exec "$JAVACMD" "$@"
